server:
  port: 3003

spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices
    password: peru2020
    username: postgres
  application:
    name: microservices